#!/usr/bin/env python3
"""Regenerate resorts.html from the consumer app's bundled catalog.

    python3 tools/build-resorts.py [path/to/SkiBuddyGemini/src/data/resorts.ts]

The catalog is the source of truth for "where Izzy can be used" (the app bundles it). Re-run this
whenever the catalog changes, then commit resorts.html. MERGE rule: the catalog lists Boston Mills
and Brandywine as two rows (split 2026-09-01); Vail markets them as one resort, so the site shows
one card — that is why the site says 91 while the catalog has 92 rows.
"""
import html, json, re, sys
from collections import Counter, OrderedDict

SRC = sys.argv[1] if len(sys.argv) > 1 else '../SkiBuddyGemini/src/data/resorts.ts'
MERGE = {('boston-mills', 'brandywine'): 'Boston Mills / Brandywine'}
STATES = {
 'AB':'Alberta','BC':'British Columbia','ON':'Ontario','QC':'Quebec',
 'CA':'California','CO':'Colorado','ID':'Idaho','ME':'Maine','MI':'Michigan','MN':'Minnesota','MO':'Missouri',
 'MT':'Montana','NC':'North Carolina','NH':'New Hampshire','NM':'New Mexico','NV':'Nevada','NY':'New York',
 'OH':'Ohio','OR':'Oregon','PA':'Pennsylvania','TN':'Tennessee','UT':'Utah','VT':'Vermont','WA':'Washington',
 'WI':'Wisconsin','WV':'West Virginia','WY':'Wyoming','AK':'Alaska','IN':'Indiana','MA':'Massachusetts','AZ':'Arizona',
}
BADGE = {'ikon': 'IKON', 'epic': 'EPIC', 'independent': 'INDY'}

src = re.sub(r'//[^\n]*', '', open(SRC, encoding='utf-8').read())
rows = [dict(id=i, name=n.replace("\\'", "'"), state=s, country=c, pas=p) for i, n, s, c, p in re.findall(
    r"\{\s*id:\s*'([^']+)',\s*name:\s*'((?:[^'\\]|\\.)+)',\s*stateOrProvince:\s*'([^']*)',\s*country:\s*'([^']*)'.*?passAffiliation:\s*'(\w+)'", src, re.S)]
for ids, label in MERGE.items():
    hits = [r for r in rows if r['id'] in ids]
    assert len(hits) == len(ids) and len({h['pas'] for h in hits}) == 1, ids
    rows = [r for r in rows if r['id'] not in ids] + [dict(hits[0], id='+'.join(ids), name=label)]
for r in rows:
    assert r['state'] in STATES, f"add {r['state']} to STATES"
    assert r['pas'] in BADGE, r

counts = Counter(r['pas'] for r in rows); total = len(rows)
groups = OrderedDict()
for r in sorted(rows, key=lambda r: (r['country'] != 'USA', STATES[r['state']], r['name'].lower())):
    groups.setdefault((r['country'], r['state']), []).append(r)

cards = []
for (country, st), rs in groups.items():
    region = f"{STATES[st]}, {'Canada' if country == 'Canada' else 'USA'}"
    items = ''.join(
        f'\n        <li class="resort is-{r["pas"]}" data-pass="{r["pas"]}" data-name="{html.escape(r["name"].lower())}">'
        f'<span class="r-name">{html.escape(r["name"])}</span><span class="r-badge">{BADGE[r["pas"]]}</span></li>'
        for r in rs)
    cards.append(f'\n      <section class="region" data-region>\n        <h3>{html.escape(region)} <span class="r-count">{len(rs)}</span></h3>\n        <ul class="resort-grid">{items}\n        </ul>\n      </section>')

page = f'''<!DOCTYPE html><html lang="en"><head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- GENERATED by tools/build-resorts.py from the consumer app catalog — edit the script, not this file. -->
<title>Izzy — {total} resorts where Izzy rides</title>
<meta name="referrer" content="strict-origin">
<meta name="description" content="Every resort where Izzy works today: {counts['ikon']} IKON, {counts['epic']} EPIC and {counts['independent']} select independent mountains across the US and Canada. Say the name and Izzy knows the lifts, trails and conditions.">
<meta property="og:title" content="Izzy — {total} resorts where Izzy rides">
<meta property="og:description" content="{counts['ikon']} IKON, {counts['epic']} EPIC and {counts['independent']} select independent resorts across the US and Canada.">
<meta property="og:type" content="website">
<meta property="og:url" content="https://izzywolf.com/resorts.html">
<meta property="og:image" content="https://izzywolf.com/assets/app-og.png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="Izzy — {total} resorts where Izzy rides">
<meta name="twitter:image" content="https://izzywolf.com/assets/app-og.png">
<link rel="icon" href="assets/app-icon.png">
<link rel="apple-touch-icon" href="assets/app-icon.png">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Hanken+Grotesk:wght@400;500;600&amp;family=Quicksand:wght@600;700&amp;display=swap" rel="stylesheet">
<link rel="stylesheet" href="styles.css">
</head>
<body>

<!-- ============================ HEADER ============================ -->
<header class="site-header">
  <div class="wrap">
    <a class="brand" href="index.html" aria-label="Izzy — home">
      <img src="assets/app-icon.png" alt="" width="38" height="38">
      Izzy
    </a>
    <nav class="nav-links" aria-label="Primary">
      <a href="index.html">For skiers</a>
      <a href="resorts.html" aria-current="page">Resorts</a>
      <a href="resort.html">For resorts</a>
      <a href="mountain.html#loop">How the loop works</a>
    </nav>
    <a class="btn btn-primary btn-sm header-cta" href="index.html#get">Get Izzy</a>
  </div>
</header>

<main id="top">

  <section class="section resorts-page">
    <div class="wrap">
      <div class="head">
        <p class="eyebrow">Where Izzy rides</p>
        <h1>{total} resorts. Say the name — Izzy knows it.</h1>
        <p class="lede">{total} mountains across the US and Canada — the IKON and EPIC resorts, plus a growing set of select independents. Pick yours in the app and Izzy answers with that mountain's lifts, trails, grooming and conditions.</p>
        <div class="pass-key" aria-hidden="true">
          <span class="r-badge is-ikon">IKON</span><span class="r-badge is-epic">EPIC</span><span class="r-badge is-independent">INDY</span>
          <span class="pass-key-note">Badges show the pass the resort belongs to. INDY = an independent, on its own pass.</span>
        </div>
      </div>

      <div class="resort-tools">
        <div class="pass-filter" role="group" aria-label="Filter by pass">
          <button type="button" data-filter="all" aria-pressed="true">All <b>{total}</b></button>
          <button type="button" data-filter="ikon" aria-pressed="false">IKON <b>{counts['ikon']}</b></button>
          <button type="button" data-filter="epic" aria-pressed="false">EPIC <b>{counts['epic']}</b></button>
          <button type="button" data-filter="independent" aria-pressed="false">INDY <b>{counts['independent']}</b></button>
        </div>
        <label class="resort-search">
          <span class="visually-hidden">Find your mountain</span>
          <input type="search" id="resortSearch" placeholder="Find your mountain…" autocomplete="off">
        </label>
      </div>
      <p class="resort-status" id="resortStatus" aria-live="polite">Showing all {total} resorts</p>
{''.join(cards)}

      <p class="resort-empty" id="resortEmpty" hidden>No resort matches that. Try a shorter name, or clear the filter.</p>

      <p class="note-line resorts-note">Not seeing your mountain? We add resorts as riders ask for them. <a href="mailto:support@izzywolf.com?subject=Add%20my%20resort%20to%20Izzy" style="color:var(--blue-bright)">Ask us to add a resort →</a></p>
    </div>
  </section>

</main>

<!-- ============================ FOOTER ============================ -->
<footer class="site-footer">
  <div class="wrap">
    <div class="foot-grid">
      <div class="foot-brand">
        <a class="brand" href="index.html">
          <img src="assets/app-icon.png" alt="" width="38" height="38">
          Izzy
        </a>
        <p>Your AI skibud for Snow and Sun. Built for the mountain — hands-free, all day, all year.</p>
      </div>
      <div class="foot-col">
        <h4>Product</h4>
        <ul>
          <li><a href="index.html">Izzy for skiers</a></li>
          <li><a href="resorts.html">Resorts</a></li>
          <li><a href="resort.html">Izzy Resort</a></li>
          <li><a href="mountain.html#loop">How the loop works</a></li>
          <li><a href="index.html#pricing">Pricing</a></li>
        </ul>
      </div>
      <div class="foot-col">
        <h4>Company</h4>
        <ul>
          <li><a href="index.html#get">Get Izzy</a></li>
          <li><a href="press.html">Press &amp; partnerships</a></li>
          <li><a href="./support.html">Support</a></li>
          <li><a href="./privacy.html">Privacy Policy</a></li>
          <li><a href="./terms.html">Terms of Use</a></li>
        </ul>
      </div>
    </div>
    <div class="foot-bottom">
      <span>© 2026 Izzy. All rights reserved.</span>
      <span><a href="mailto:support@izzywolf.com">support@izzywolf.com</a></span>
    </div>
  </div>
</footer>

<script>
  // Pass filter + name search. The list is static HTML, so it reads fine without JS.
  (function () {{
    var buttons = document.querySelectorAll('.pass-filter button');
    var input = document.getElementById('resortSearch');
    var status = document.getElementById('resortStatus');
    var empty = document.getElementById('resortEmpty');
    var items = document.querySelectorAll('.resort');
    var regions = document.querySelectorAll('[data-region]');
    var filter = 'all';
    function apply() {{
      var q = input.value.trim().toLowerCase(), shown = 0;
      items.forEach(function (li) {{
        var ok = (filter === 'all' || li.dataset.pass === filter) && (!q || li.dataset.name.indexOf(q) !== -1);
        li.hidden = !ok; if (ok) shown++;
      }});
      regions.forEach(function (s) {{ s.hidden = !s.querySelector('.resort:not([hidden])'); }});
      empty.hidden = shown !== 0;
      var label = filter === 'all' ? 'resorts' : (filter === 'independent' ? 'INDY' : filter.toUpperCase()) + ' resorts';
      status.textContent = shown === {total} ? 'Showing all {total} resorts' : 'Showing ' + shown + ' of {total} ' + label + (q ? ' matching “' + input.value.trim() + '”' : '');
    }}
    buttons.forEach(function (b) {{
      b.addEventListener('click', function () {{
        filter = b.dataset.filter;
        buttons.forEach(function (x) {{ x.setAttribute('aria-pressed', x === b ? 'true' : 'false'); }});
        apply();
      }});
    }});
    input.addEventListener('input', apply);
  }})();
</script>
</body></html>
'''
open('resorts.html', 'w', encoding='utf-8').write(page)
print(f"resorts.html: {total} cards ({dict(counts)}), {len(groups)} regions")
